### ISSUE TITLE
CDN reference

### ISSUE THREAD

**Issue by rubychilds** [nature-of-code/noc-examples-p5.js#44]
Just working on the python port and comparing to JS version. Have noticed that the source for p5.js is referred to as `src="//cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.22/p5.js"` Seems to have no `https`. Not sure if this is a fault, or simply intentional (maybe I need to do additional setup), as when running in Chrome, it defaults to try to find a local file and hence wont work as an example unless this is changed. Let me know if its an issue and can try change it throughout

**Comment by shiffman** [comment]
I have not written the `index.html` files with any careful plan and what's there is almost entirely accidental.  I perhaps have a slight preference for referencing a local `p5.js` file in a `libraries` directory so that the repo can be cloned and used offline, but maybe CDN is better.  In any case, if you want to suggest any corrections or make things more consistent I say go for it!

**Comment by rubychilds** [comment]
Done :) Completely agree aka referencing localyl, but I guess if this is for people to learn p5.js CDN maybe easy than setting it up locally @shiffman  Thank you!

**Comment by shiffman** [comment]
Well, almost 6 years later I now prefer referencing the CDN which should hopefully be what all the examples do now! Hope all is well @rubychilds!
